version: '3.1'

services:

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - c_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: chushi_development

  cache:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - c_redis_data:/data
#
#  nats:
#    image: nats
#    ports:
#      - "8222:8222"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  opa:
    image: openpolicyagent/opa
    ports:
      - "8181:8181"
    command: run --server --addr :8181

  timber:
    image: ghcr.io/chushi-io/timber:main
    ports:
      - "8080:8080"
    volumes:
      - timber_data:/timber/data
    command: /bin/timber --debug

#
#  agent:
#    image: ghcr.io/
volumes:
  minio_data:
  c_postgres_data:
  c_redis_data:
  timber_data:
