// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        uuid.UUID
	Name      *string
	Token     *string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	LastSeen  pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Agent struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	OrganizationID pgtype.UUID
	Status         *string
	OauthClientID  *string
	Name           *string
}

type ConfigurationVersion struct {
	ID          uuid.UUID
	WorkspaceID pgtype.UUID
	Source      *string
	Speculative *bool
	Status      *string
	UploadUrl   *string
	Provisional *bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OauthClient struct {
	ID        string
	Secret    *string
	Domain    *string
	Data      *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type OauthToken struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Code      *string
	Access    *string
	Refresh   *string
	Data      *string
}

type Organization struct {
	ID                       uuid.UUID
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	DeletedAt                pgtype.Timestamptz
	Name                     *string
	AllowAutoCreateWorkspace *bool
	Type                     *string
	DefaultAgentID           *string
}

type OrganizationUser struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Role           *string
}

type OrganizationVariable struct {
	OrganizationID string
	VariableID     string
}

type OrganizationVariableSet struct {
	OrganizationID string
	VariableSetID  string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Run struct {
	ID               uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Status           *string
	WorkspaceID      pgtype.UUID
	Add              *int64
	Change           *int64
	Destroy          *int64
	ManagedResources *int64
	AgentID          pgtype.UUID
	CompletedAt      pgtype.Timestamptz
	Operation        *string
	SourceRunID      *string
}

type User struct {
	ID                 uuid.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Email              *string
	Password           *string
	Active             *bool
	ConfirmSelector    *string
	ConfirmVerifier    *string
	Confirmed          *bool
	AttemptCount       *int64
	LastAttempt        pgtype.Timestamptz
	Locked             pgtype.Timestamptz
	RecoverSelector    *string
	RecoverVerifier    *string
	RecoverTokenExpiry pgtype.Timestamptz
	Oauth2Uid          *string
	Oauth2Provider     *string
	Oauth2AccessToken  *string
	Oauth2RefreshToken *string
	OAuth2Expiry       pgtype.Timestamptz
	TotpSecretKey      *string
	SmsPhoneNumber     *string
	SmsSeedPhoneNumber *string
	RecoveryCodes      *string
	Oauth2Expiry       pgtype.Timestamptz
	RecoveVerifier     *string
}

type UserLanguage struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type Variable struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Type           *string
	WorkspaceID    pgtype.UUID
	Name           *string
	Value          *string
	Description    *string
	Sensitive      *bool
	VariableSetID  pgtype.UUID
	OrganizationID *string
}

type VariableSet struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	OrganizationID *string
	Name           *string
	Description    *string
	AutoAttach     *bool
	Priority       *int32
}

type VcsConnection struct {
	ID                           uuid.UUID
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	DeletedAt                    pgtype.Timestamptz
	Name                         *string
	Provider                     *string
	GithubType                   *string
	GithubPersonalAccessToken    *string
	GithubApplicationID          *string
	GithubApplicationSecret      *string
	GithubOauthApplicationID     *string
	GithubOauthApplicationSecret *string
	OrganizationID               pgtype.UUID
	WebhookID                    *string
	WebhookSecret                *string
}

type Workspace struct {
	ID                     uuid.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	Name                   *string
	AllowDestroy           *bool
	AutoApply              *bool
	AutoDestroyAt          pgtype.Timestamptz
	ExecutionMode          *string
	VcsSource              *string
	VcsBranch              *string
	VcsPatterns            *string
	VcsPrefixes            *string
	VcsWorkingDirectory    *string
	Version                *string
	Locked                 *bool
	LockBy                 *string
	LockAt                 *string
	LockID                 *string
	OrganizationID         pgtype.UUID
	AgentID                pgtype.UUID
	DriftDetectionEnabled  *bool
	DriftDetectionSchedule *string
	VcsConnectionID        *string
}

type WorkspaceVariable struct {
	WorkspaceID string
	VariableID  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type WorkspaceVariableSet struct {
	WorkspaceID   string
	VariableSetID string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}
