domain: cloud.chushi.io
timber_url: https://timber.chushi.io

storage:
  provider: aws
  buckets:
    applies: ""
    configuration_versions: ""
    modules: ""
    plans: ""
    policies: ""
    providers: ""
    state_versions: ""

github:
  application:
    name: