domain: cloud.chushi.io
timber_url: https://timber.chushi.io

storage:
  provider: AWS
  buckets:
    configuration_versions: chushi-prod-configuration-versions-eiuiuaiq
    modules: chushi-prod-modules-kwsfiktk
    plans: chushi-prod-plans-cpddaiaq
    policies: chushi-prod-policies-iwniwacq
    providers: chushi-prod-providers-pvndellc
    state_versions: chushi-prod-state-versions-jlppyecr