domain: test.chushi.io
oidc_private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQ2pHQwL6efKQA
  /VQuN8QVjiHTJSbH5qU7r9U1zF98Y7b3aAnjzyiUlVRwwJtXbz0ewBFEkKRMaocL
  5nip2hvrGv1ZVRTNZ3Mh5dxb2oHvXR8x8YN/uBJkwtK6lfcVvw4z3AuS+c661UYg
  5aWlK1j5Q0kmNcQht7vI1crBIm1WWjGVzLzU4iex5PObFyORLWQpGvcjIWLRHUyZ
  OBhGDITpOsdvuSTWnEUIWGAoZ4hdKeWHidsiHePAFV/rHaEBbKHnFVPZ9exDNWZ/
  EYt3LNAFYVHeayOmS4HTnuxF6CygM8CnP5TtMce6uDiCaqaHzPB1IRh/8l2Ca8YY
  CZdkg3lVAgMBAAECggEAETyfIPw6i/7IoLXhQLJxiHKwIyqQLM3B5ujE6MLy20oP
  fuCJqgRRQRIIY6KoL2skcpxynTBvnuIb1/hjDpsybd21LK5AIHbgb0FdRZqfDQ/b
  Om/7flfFJnO9y8OcuAeKNu8Um9vqGxlTx455QUx2jciz1md3+ToEt+qNG6t2HDsA
  0C/lCCkvkgz4AbT/e/5LVnkPNnKc3uQ7jcsPPykSuKI5S+BUhDSEusuazEkxFLYw
  ldM33Wwuh7r4veAVIIrc8weaZlyY/29cUHsYXQgHQri5jLZtwYyLyJ5xTeQC/QrE
  FkU/bgOWOEKHU2qC+EiHfSKrWZGWW0bx5vDcRGTecQKBgQDtOnzfOZQY6aPQF7T3
  BW6K6RxkF9QHYjjKJFvtXvtZRCx+hWfFBtgrI5qPdJuRc7+wu87f5QStNXdKRFGz
  bix8r9GdS+XAMH7qnLLX7OuW/j9K/SVOVLG8jUfJehZkXzGPKDnMREbJwRJ9qAA9
  S3LWStZ3w4bSBefM/9i6cScD3wKBgQDhYUyDhmmZBdWByDYBfDZ0m8ItSdfb34Y5
  vK2osjGH8+Havp8NlUEyuiDeTP7w1tH38oM9sqoo1rqwBZHQ2DOnwgK/BO21Sp8O
  zhCV2TiTbln6NAHTbTVUWKzE/Z/V6TGyhri5s1bbL2rBzcuvV3LWnMQ5i3SFsKsu
  sltYq12JSwKBgFDkD65iSNCR4ozTeJ5+mKn/QPIUefUmley/pyTyrUxMBcwCm1bA
  tbdIBa0C+wUG7gdKkwkfY4/YWlvVnfJMEBlYLmaveaEmKDDBy+362H59JYHhffYO
  xShhGGhoG/iPySticQrpASZMkoyMW8CK2JafoC/oWTGGV/s8Bl/Us5QLAoGANv08
  Y+LJpPJNc4rb0mTyDGVsbQxVRGo3H6MvY7eGajtQ4cQcnn3KGIxdNJ/om+5t8GcV
  KlqLNceeaRAS0bfOcqHddanILbF1OXGBjm4fZalI/sjtoR5GIrw3+yA+fTyWSY6h
  R33ANV5OV9bUWYWmmUJKhhfGaFAAlDYkH3BANB0CgYEAoUdu0DFnF6maFnI+TxaN
  6qC166bPnURJWBW9C6FiHzFb47YgIOrx/TiyAsMdY8QUzLpVIhWWH0kCD0625Bkz
  V/+2xdMO+MY3P7/eNKf6/eY9gBKXjNASitkRQJaDxgWUoworL7tT5TUilhwakHtV
  YMw8jWcIRd0CY3PJymODZH8=
  -----END PRIVATE KEY-----
private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQ2pHQwL6efKQA
  /VQuN8QVjiHTJSbH5qU7r9U1zF98Y7b3aAnjzyiUlVRwwJtXbz0ewBFEkKRMaocL
  5nip2hvrGv1ZVRTNZ3Mh5dxb2oHvXR8x8YN/uBJkwtK6lfcVvw4z3AuS+c661UYg
  5aWlK1j5Q0kmNcQht7vI1crBIm1WWjGVzLzU4iex5PObFyORLWQpGvcjIWLRHUyZ
  OBhGDITpOsdvuSTWnEUIWGAoZ4hdKeWHidsiHePAFV/rHaEBbKHnFVPZ9exDNWZ/
  EYt3LNAFYVHeayOmS4HTnuxF6CygM8CnP5TtMce6uDiCaqaHzPB1IRh/8l2Ca8YY
  CZdkg3lVAgMBAAECggEAETyfIPw6i/7IoLXhQLJxiHKwIyqQLM3B5ujE6MLy20oP
  fuCJqgRRQRIIY6KoL2skcpxynTBvnuIb1/hjDpsybd21LK5AIHbgb0FdRZqfDQ/b
  Om/7flfFJnO9y8OcuAeKNu8Um9vqGxlTx455QUx2jciz1md3+ToEt+qNG6t2HDsA
  0C/lCCkvkgz4AbT/e/5LVnkPNnKc3uQ7jcsPPykSuKI5S+BUhDSEusuazEkxFLYw
  ldM33Wwuh7r4veAVIIrc8weaZlyY/29cUHsYXQgHQri5jLZtwYyLyJ5xTeQC/QrE
  FkU/bgOWOEKHU2qC+EiHfSKrWZGWW0bx5vDcRGTecQKBgQDtOnzfOZQY6aPQF7T3
  BW6K6RxkF9QHYjjKJFvtXvtZRCx+hWfFBtgrI5qPdJuRc7+wu87f5QStNXdKRFGz
  bix8r9GdS+XAMH7qnLLX7OuW/j9K/SVOVLG8jUfJehZkXzGPKDnMREbJwRJ9qAA9
  S3LWStZ3w4bSBefM/9i6cScD3wKBgQDhYUyDhmmZBdWByDYBfDZ0m8ItSdfb34Y5
  vK2osjGH8+Havp8NlUEyuiDeTP7w1tH38oM9sqoo1rqwBZHQ2DOnwgK/BO21Sp8O
  zhCV2TiTbln6NAHTbTVUWKzE/Z/V6TGyhri5s1bbL2rBzcuvV3LWnMQ5i3SFsKsu
  sltYq12JSwKBgFDkD65iSNCR4ozTeJ5+mKn/QPIUefUmley/pyTyrUxMBcwCm1bA
  tbdIBa0C+wUG7gdKkwkfY4/YWlvVnfJMEBlYLmaveaEmKDDBy+362H59JYHhffYO
  xShhGGhoG/iPySticQrpASZMkoyMW8CK2JafoC/oWTGGV/s8Bl/Us5QLAoGANv08
  Y+LJpPJNc4rb0mTyDGVsbQxVRGo3H6MvY7eGajtQ4cQcnn3KGIxdNJ/om+5t8GcV
  KlqLNceeaRAS0bfOcqHddanILbF1OXGBjm4fZalI/sjtoR5GIrw3+yA+fTyWSY6h
  R33ANV5OV9bUWYWmmUJKhhfGaFAAlDYkH3BANB0CgYEAoUdu0DFnF6maFnI+TxaN
  6qC166bPnURJWBW9C6FiHzFb47YgIOrx/TiyAsMdY8QUzLpVIhWWH0kCD0625Bkz
  V/+2xdMO+MY3P7/eNKf6/eY9gBKXjNASitkRQJaDxgWUoworL7tT5TUilhwakHtV
  YMw8jWcIRd0CY3PJymODZH8=
  -----END PRIVATE KEY-----
