name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  helm:
#    name: Test Helm Chart
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: azure/setup-helm@v3
#        with:
#          version: v3.10.3
#      - run: helm lint --strict deploy/charts/chushi

  rubocop:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec rubocop

  api-integration-tests:
    name: "API Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec